# Procesamiento de Datos

In [1]:
import pandas as pd
import numpy as np
import json
import re

## Museos México

In [2]:
museos = {'FridaKahlo':'data/museo_frida_kahlo/dataset.csv',
           'MUNAL':'data/museo_nacional_de_arte/dataset.csv', 
           'Soumaya': 'data/museo_soumaya_fundaci_n_carlos_slim/dataset.csv', 
           'Blaisten': 'data/colecci_n_blaisten/dataset.csv', 
           'MACAY': 'data/museo_de_arte_contempor_neo_ateneo_de_yucat_n_macay_fernando_garc_a_ponce/dataset.csv', 
           'Arocena': 'data/museo_arocena/dataset.csv'}

In [3]:
dataframes = {}
for name, filename in museos.items():
    dataframes[name] = pd.read_csv(filename)

In [4]:
dataframes.keys()

dict_keys(['FridaKahlo', 'MUNAL', 'Soumaya', 'Blaisten', 'MACAY', 'Arocena'])

In [5]:
common_all = set.intersection(*[set(df.columns) for df in dataframes.values()])
common_all

{'Creador',
 'Derechos',
 'Dimensiones físicas',
 'Título',
 'artista',
 'descripcion',
 'imagen',
 'link',
 'titulo'}

In [6]:
df1 = pd.concat(dataframes, names=["museo"])

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1711 entries, ('FridaKahlo', np.int64(0)) to ('Arocena', np.int64(125))
Data columns (total 67 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   titulo                              1711 non-null   object
 1   artista                             1711 non-null   object
 2   link                                1711 non-null   object
 3   descripcion                         1184 non-null   object
 4   imagen                              1711 non-null   object
 5   Creador                             1402 non-null   object
 6   Derechos                            1221 non-null   object
 7   Dimensiones físicas                 1450 non-null   object
 8   Enlace externo                      396 non-null    object
 9   Fecha                               163 non-null    object
 10  Fecha de creación                   1348 non-null   object
 11  Firma de alta costura               2 non-null      object
 12  Fotógrafo                           22 non-null     object
 13  Lugar                               24 non-null     object
 14  Lugar de creación                   110 non-null    object
 15  Lugar de fallecimiento del creador  182 non-null    object
 16  Lugar de nacimiento del creador     222 non-null    object
 17  Nacionalidad del creador            232 non-null    object
 18  Sexo del creador                    265 non-null    object
 19  Temporada                           2 non-null      object
 20  Tipo                                707 non-null    object
 21  Técnica artística                   589 non-null    object
 22  Título                              1711 non-null   object
 23  Vida del creador                    257 non-null    object
 24  description                         39 non-null     object
 25  description extent                  40 non-null     object
 26  description source                  40 non-null     object
 27  medium extent                       44 non-null     object
 28  medium source                       44 non-null     object
 29  original title                      1 non-null      object
 30  original title extent               1 non-null      object
 31  original title source               1 non-null      object
 32  painter                             127 non-null    object
 33  photographer                        12 non-null     object
 34  provenance                          43 non-null     object
 35  provenance extent                   43 non-null     object
 36  provenance source                   43 non-null     object
 37  tag                                 1 non-null      object
 38  tag extent                          1 non-null      object
 39  tag source                          1 non-null      object
 40  theme                               3 non-null      object
 41  theme extent                        3 non-null      object
 42  theme source                        3 non-null      object
 43  title (spanish)                     3 non-null      object
 44  title (spanish) extent              3 non-null      object
 45  title (spanish) source              3 non-null      object
 46  Illuminator                         2 non-null      object
 47  Original Spanish object note        126 non-null    object
 48  Original title                      127 non-null    object
 49  Portraitist                         2 non-null      object
 50  Provenance                          127 non-null    object
 51  Sculptor                            7 non-null      object
 52  Ayuda                               771 non-null    object
 53  Género artístico                    196 non-null    object
 54  Manifestación artística             648 non-null    object
 55  Movimiento artístico                16 non-null     object
 56  Persona representada                208 non-null    object
 57  Tema representado                   390 non-null    object
 58  Ubicación representada              5 non-null      object
 59  Colaborador                         23 non-null     object
 60  Fuente original                     1 non-null      object
 61  Palabras clave del asunto           255 non-null    object
 62  "La Ruptura"                        51 non-null     object
 63  Exhibición                          119 non-null    object
 64  La Ruptura                          68 non-null     object
 65  Origen                              119 non-null    object
 66  Transcripción                       1 non-null      object
dtypes: object(67)
memory usage: 940.3+ KB

In [8]:
print(df1.count().sort_values(ascending=False).to_string())

titulo                                1711
artista                               1711
link                                  1711
imagen                                1711
Título                                1711
Dimensiones físicas                   1450
Creador                               1402
Fecha de creación                     1348
Derechos                              1221
descripcion                           1184
Ayuda                                  771
Tipo                                   707
Manifestación artística                648
Técnica artística                      589
Enlace externo                         396
Tema representado                      390
Sexo del creador                       265
Vida del creador                       257
Palabras clave del asunto              255
Nacionalidad del creador               232
Lugar de nacimiento del creador        222
Persona representada                   208
Género artístico                       196
Lugar de fallecimiento del creador     182
Fecha                                  163
painter                                127
Original title                         127
Provenance                             127
Original Spanish object note           126
Exhibición                             119
Origen                                 119
Lugar de creación                      110
La Ruptura                              68
"La Ruptura"                            51
medium source                           44
medium extent                           44
provenance extent                       43
provenance source                       43
provenance                              43
description extent                      40
description source                      40
description                             39
Lugar                                   24
Colaborador                             23
Fotógrafo                               22
Movimiento artístico                    16
photographer                            12
Sculptor                                 7
Ubicación representada                   5
theme                                    3
theme source                             3
title (spanish)                          3
theme extent                             3
title (spanish) source                   3
title (spanish) extent                   3
Firma de alta costura                    2
Illuminator                              2
Portraitist                              2
Temporada                                2
original title source                    1
original title extent                    1
original title                           1
tag source                               1
tag extent                               1
tag                                      1
Fuente original                          1
Transcripción                            1

In [9]:
museums_with_column = []
for museum_name, df in dataframes.items():
    if 'Ayuda' in df.columns:
        museums_with_column.append(museum_name)

print(museums_with_column)

['Soumaya']

In [10]:
dataframes['Soumaya']['Ayuda'].value_counts()

Ayuda
Óleo sobre lienzo                                                                                                                                                        261
Óleo sobre tabla                                                                                                                                                          69
canvas                                                                                                                                                                    53
Óleo sobre lámina de cobre                                                                                                                                                15
Óleo sobre lámina de zinc                                                                                                                                                 12
                                                                                                                                                                        ...
Blusa de viscosa con hilos de seda. Falda de castor con aplicación de chaquira, lentejuela de plata bordada y de cola, ribete de raso de seda. Faja de rebozo de seda      1
Cera modelada y policromada, lienzo, hilos, chaquiras de vidrio, barro, fibra vegetal. Base de madera                                                                      1
Tinta, carboncillo y pastel sobre papel                                                                                                                                    1
Calcografía                                                                                                                                                                1
Pastel sobre papel montado en cartón                                                                                                                                       1
Name: count, Length: 251, dtype: int64

In [11]:
def unify_priority_columns(df, new_col, cols_priority):
    cols = [c for c in cols_priority if c in df.columns]

    if not cols:
        return df

    df[new_col] = df[cols[0]]

    # rellena con las siguientes
    for col in cols[1:]:
        df[new_col] = df[new_col].fillna(df[col])

    return df

def unify_columns(df):
    df = unify_priority_columns(df, "titulo", [
        "titulo",
        "Título",
        "original title",
        "title (spanish)",
        "Original Spanish object note"
    ])
    df = unify_priority_columns(df, "descripcion", [
        "descripcion",
        "description"
    ])

    df = unify_priority_columns(df, "tipo_obra", [
        "Tipo",
        "Manifestación artística"
    ])


    df = unify_priority_columns(df, "tecnica", [
        "Técnica artística",
        "Ayuda"
    ])


    df = unify_priority_columns(df, "tema", [
        "Tema representado",
        "theme"
    ])

    df = unify_priority_columns(df, "genero_artistico", [
        "Género artístico",
        "Movimiento artístico"
    ])

  
    df = unify_priority_columns(df, "origen", [
        "Origen",
        "Lugar de creación",
        "Lugar"
    ])


    df = unify_priority_columns(df, "fecha", [
        "Fecha de creación",
        "Fecha"
    ])

    df = unify_priority_columns(df, "artista", [
        "artista",
        "Creador",
        "painter",
        "Sculptor",
        "Photographer",
        "Fotógrafo"
    ])

    cols_to_drop = [
        "Título", "original title", "title (spanish)", "Original Spanish object note",
        "description",
        "Tipo", "Manifestación artística",
        "Técnica artística", "Ayuda",
        "theme",
        "Movimiento artístico",
        "Lugar de creación", "Lugar",
        "Fecha",
        "Creador", "painter", "Sculptor", "Photographer", "Fotógrafo"
    ]

    cols_to_drop = [c for c in cols_to_drop if c in df.columns]

    df = df.drop(columns=cols_to_drop)

    return df

def clean_strings(df):
    def limpiar(x):
        if isinstance(x, str):
            return x.strip()
        return x

    return df.applymap(limpiar)
def add_museum_column(df):
    df = df.copy()
    df["museo"] = df.index.get_level_values(0)
    return df
def drop_sparse_columns(df, threshold=50):
    cols_to_drop = [col for col in df.columns if df[col].count() < threshold]
    return df.drop(columns=cols_to_drop)
def clean_pipeline(df):
    #print("ANTES:", df.shape)
    #print(df[["Fecha", "Fecha de creación"]].count())

    df = unify_columns(df)

    #print("DESPUÉS:", df.shape)
    #print(df["fecha"].count())
    df = clean_strings(df)
    df = add_museum_column(df)
    df = drop_sparse_columns(df, 70)

    return df

In [12]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1711 entries, ('FridaKahlo', np.int64(0)) to ('Arocena', np.int64(125))
Data columns (total 67 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   titulo                              1711 non-null   object
 1   artista                             1711 non-null   object
 2   link                                1711 non-null   object
 3   descripcion                         1184 non-null   object
 4   imagen                              1711 non-null   object
 5   Creador                             1402 non-null   object
 6   Derechos                            1221 non-null   object
 7   Dimensiones físicas                 1450 non-null   object
 8   Enlace externo                      396 non-null    object
 9   Fecha                               163 non-null    object
 10  Fecha de creación                   1348 non-null   object
 11  Firma de alta costura               2 non-null      object
 12  Fotógrafo                           22 non-null     object
 13  Lugar                               24 non-null     object
 14  Lugar de creación                   110 non-null    object
 15  Lugar de fallecimiento del creador  182 non-null    object
 16  Lugar de nacimiento del creador     222 non-null    object
 17  Nacionalidad del creador            232 non-null    object
 18  Sexo del creador                    265 non-null    object
 19  Temporada                           2 non-null      object
 20  Tipo                                707 non-null    object
 21  Técnica artística                   589 non-null    object
 22  Título                              1711 non-null   object
 23  Vida del creador                    257 non-null    object
 24  description                         39 non-null     object
 25  description extent                  40 non-null     object
 26  description source                  40 non-null     object
 27  medium extent                       44 non-null     object
 28  medium source                       44 non-null     object
 29  original title                      1 non-null      object
 30  original title extent               1 non-null      object
 31  original title source               1 non-null      object
 32  painter                             127 non-null    object
 33  photographer                        12 non-null     object
 34  provenance                          43 non-null     object
 35  provenance extent                   43 non-null     object
 36  provenance source                   43 non-null     object
 37  tag                                 1 non-null      object
 38  tag extent                          1 non-null      object
 39  tag source                          1 non-null      object
 40  theme                               3 non-null      object
 41  theme extent                        3 non-null      object
 42  theme source                        3 non-null      object
 43  title (spanish)                     3 non-null      object
 44  title (spanish) extent              3 non-null      object
 45  title (spanish) source              3 non-null      object
 46  Illuminator                         2 non-null      object
 47  Original Spanish object note        126 non-null    object
 48  Original title                      127 non-null    object
 49  Portraitist                         2 non-null      object
 50  Provenance                          127 non-null    object
 51  Sculptor                            7 non-null      object
 52  Ayuda                               771 non-null    object
 53  Género artístico                    196 non-null    object
 54  Manifestación artística             648 non-null    object
 55  Movimiento artístico                16 non-null     object
 56  Persona representada                208 non-null    object
 57  Tema representado                   390 non-null    object
 58  Ubicación representada              5 non-null      object
 59  Colaborador                         23 non-null     object
 60  Fuente original                     1 non-null      object
 61  Palabras clave del asunto           255 non-null    object
 62  "La Ruptura"                        51 non-null     object
 63  Exhibición                          119 non-null    object
 64  La Ruptura                          68 non-null     object
 65  Origen                              119 non-null    object
 66  Transcripción                       1 non-null      object
dtypes: object(67)
memory usage: 940.3+ KB

In [13]:
print(df1.shape)

(1711, 67)

In [14]:
df1 = clean_pipeline(df1)

C:\Users\roxan\AppData\Local\Temp\ipykernel_41300\2677936922.py:96: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(limpiar)

In [15]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1711 entries, ('FridaKahlo', np.int64(0)) to ('Arocena', np.int64(125))
Data columns (total 29 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   titulo                              1711 non-null   object
 1   artista                             1711 non-null   object
 2   link                                1711 non-null   object
 3   descripcion                         1184 non-null   object
 4   imagen                              1711 non-null   object
 5   Derechos                            1221 non-null   object
 6   Dimensiones físicas                 1450 non-null   object
 7   Enlace externo                      396 non-null    object
 8   Fecha de creación                   1348 non-null   object
 9   Lugar de fallecimiento del creador  182 non-null    object
 10  Lugar de nacimiento del creador     222 non-null    object
 11  Nacionalidad del creador            232 non-null    object
 12  Sexo del creador                    265 non-null    object
 13  Vida del creador                    257 non-null    object
 14  Original title                      127 non-null    object
 15  Provenance                          127 non-null    object
 16  Género artístico                    196 non-null    object
 17  Persona representada                208 non-null    object
 18  Tema representado                   390 non-null    object
 19  Palabras clave del asunto           255 non-null    object
 20  Exhibición                          119 non-null    object
 21  Origen                              119 non-null    object
 22  tipo_obra                           1355 non-null   object
 23  tecnica                             1360 non-null   object
 24  tema                                393 non-null    object
 25  genero_artistico                    212 non-null    object
 26  origen                              253 non-null    object
 27  fecha                               1511 non-null   object
 28  museo                               1711 non-null   object
dtypes: object(29)
memory usage: 432.4+ KB

In [16]:
df1.drop(columns=['Derechos', 'link', 'Enlace externo', 'Vida del creador', 'Original title', 'Provenance', 'Persona representada', 'Tema representado', 'Exhibición', 'Origen', 'Fecha de creación', 'Género artístico'], inplace=True)

In [17]:
def rename_columns(df):
    return df.rename(columns={
        "titulo": "title",
        "fecha": "date",
        "artista": "artist",
        "descripcion": "description",
        "imagen": "image_path",
        "tecnica": "technique",
        "Dimensiones físicas": "dimensions",
        "Nacionalidad del creador": "artist_nationality",
        "Sexo del creador": "artist_sex",
        "Lugar de nacimiento del creador": "artist_birthplace",
        "Lugar de fallecimiento del creador": "artist_deathplace",
        "genero_artistico": "genre",
        "Palabras clave del asunto": "keywords",
        "tipo_obra": "type",
        "tema": "theme",
        "museo": "museum",
        "origen": "origin"
    })

In [18]:
df1 = rename_columns(df1)

In [19]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1711 entries, ('FridaKahlo', np.int64(0)) to ('Arocena', np.int64(125))
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               1711 non-null   object
 1   artist              1711 non-null   object
 2   description         1184 non-null   object
 3   image_path          1711 non-null   object
 4   dimensions          1450 non-null   object
 5   artist_deathplace   182 non-null    object
 6   artist_birthplace   222 non-null    object
 7   artist_nationality  232 non-null    object
 8   artist_sex          265 non-null    object
 9   keywords            255 non-null    object
 10  type                1355 non-null   object
 11  technique           1360 non-null   object
 12  theme               393 non-null    object
 13  genre               212 non-null    object
 14  origin              253 non-null    object
 15  date                1511 non-null   object
 16  museum              1711 non-null   object
dtypes: object(17)
memory usage: 272.0+ KB

In [20]:
df1['dimensions'].value_counts()

dimensions
w50 x h65 cm (Complete)                                19
Formato rectangular vertical. Objeto bidimensional.    18
24.2x19.2cm                                            14
w56 x h76 cm (Complete)                                10
w76 x h56 cm (Complete)                                10
                                                       ..
H 55.5 x W: 23 x ? 19.8 CM                              1
w1622 x h1052 mm (complete)                             1
85 x 64 x 2 cm                                          1
H:53.5 X W:52.5 X D:6.5                                 1
63 x 26 x 20 cm                                         1
Name: count, Length: 1321, dtype: int64

## Normalizar Valores

### Dimensiones

In [21]:
def parse_dimensions(text):
    if not isinstance(text, str) or text.strip() == "":
        return np.nan, np.nan, np.nan

    text = text.lower()

    if "mm" in text:
        factor = 0.1 
    else:
        factor = 1  

    nums = re.findall(r"\d+\.?\d*", text)
    nums = [float(n) * factor for n in nums]

    if len(nums) == 0:
        return np.nan, np.nan, np.nan

    elif len(nums) == 1:
        return nums[0], np.nan, np.nan

    elif len(nums) == 2:
        return nums[0], nums[1], np.nan

    else:
        return nums[0], nums[1], nums[2]

In [22]:
df1[["width_cm", "height_cm", "depth_cm"]] = df1["dimensions"].apply(
    lambda x: pd.Series(parse_dimensions(x))
)

In [23]:
df1['width_cm'].value_counts()

width_cm
50.0     24
100.0    19
56.0     17
60.0     17
24.2     15
         ..
37.7      1
214.0     1
44.3      1
84.4      1
75.6      1
Name: count, Length: 747, dtype: int64

### Tipo

In [24]:
print(df1['type'].value_counts().to_string())

type
Pintura                                          738
Painting                                         136
PAINTING                                         111
Escultura                                         73
Fotografía                                        31
Photograph                                        21
Litografía                                        20
Acrílico sobre tela                               19
Collage                                           19
Serigrafía                                        17
pintura                                           16
Pintura al óleo.                                  12
Mixta sobre tela                                  11
Serigrafía/ Collage                               10
Pintura de panel / Óleo sobre madera               8
Pintura al óleo                                    8
Dibujo                                             7
sculpture                                          6
Óleo sobre tela                                    5
Textil                                             5
Orfebrerí­a                                        4
Pintura de panel                                   4
Grabado                                            4
Ecultura                                           4
lithograph                                         3
Foto panorámica                                    3
Técnica mixta                                      3
Collage sobre triplay                              2
Collar                                             2
Artes decorativas                                  2
Técnica mixta sobre tela                           2
Huipil                                             2
Collage sobre cartulina                            2
Collage sobre cartón                               2
Mixta sobre madera                                 2
Pintura de panel / Óleo sobre madera.              2
Sculpture                                          2
Relief                                             2
Talla en marfil                                    2
Corsé, vestido                                     1
Corsé                                              1
Vestido                                            1
Drawing                                            1
Bordado                                            1
grabado                                            1
Manuscript                                         1
Featherwork                                        1
Corsé, falda                                       1
Estuche-relicario                                  1
Bota                                               1
Huipil Juchiteco ´de carita´                       1
Gafas de sol                                       1
Aparatos ortopédicos                               1
Rebozo                                             1
Aparato ortopédico                                 1
drawing                                            1
Zapatillas                                         1
Tocado                                             1
DRAWING                                            1
SCULPTURE                                          1
PHOTOGRAPH                                         1
Gouache sobre papel                                1
Collage sobre cartón corrugado                     1
dibujo                                             1
Collage sobre tela                                 1
Serigrafía impresa a 9 tintas                      1
Collage sobre cartulina ilustración                1
Acrílico sobre triplay                             1
Acrílico sobre relieve sobre madera                1
Pintura de panel / Óleo y temple sobre madera      1
Abanico                                            1
Pintura de Panel.                                  1

In [25]:
def normalize_type(text):
    if not isinstance(text, str):
        return np.nan

    text = text.lower().strip()

    if any(word in text for word in [
        "pintura", "painting", "óleo", "oleo", "acrílico"
    ]):
        return "pintura"

    if any(word in text for word in [
        "escultura", "sculpture", "relief", "talla", "Ecultura"
    ]):
        return "escultura"
    
    if any(word in text for word in [
        "fotografía", "photograph", "foto"
    ]):
        return "fotografía"

    if any(word in text for word in [
        "grabado", "litografía", "lithograph", "serigrafía"
    ]):
        return "impresiones"

    if any(word in text for word in [
        "dibujo", "drawing"
    ]):
        return "dibujo"

    if any(word in text for word in [
        "textil", "huipil", "rebozo", "vestido", "corsé"
    ]):
        return "textil"
    
    if any(word in text for word in [
        "mixta", "collage"
    ]):
        return "mixta"

    if any(word in text for word in [
        "collar", "gafas", "abanico", "bota", "estuche"
    ]):
        return "objeto"

    return "otro"

In [26]:
df1["type_norm"] = df1["type"].apply(normalize_type)

In [27]:
df1['type_norm'].value_counts()

type_norm
pintura        1063
escultura        86
fotografía       56
impresiones      56
mixta            46
otro             18
textil           13
dibujo           11
objeto            6
Name: count, dtype: int64

In [28]:
df1[df1['type_norm'] == 'otro']['type'].value_counts()

type
Ecultura                4
Orfebrerí­a             4
Artes decorativas       2
Aparato ortopédico      1
Zapatillas              1
Tocado                  1
Aparatos ortopédicos    1
Featherwork             1
Manuscript              1
Gouache sobre papel     1
Bordado                 1
Name: count, dtype: int64

### Fecha

In [29]:
print(df1['date'].value_counts().to_string())

date
1000                           41
Siglo XVIII                    40
1750/1800                      28
1976 - 1976                    19
1950                           19
1850/1850                      18
Siglo XVI                      16
Siglo XVII                     15
1850/1900                      15
1984 - 1984                    14
1750/1830                      13
1770/1800                      13
1922                           11
1985 - 1985                    11
1650/1650                      10
2018                           10
1840/1860                      10
1943                            9
1670/1730                       9
1947                            9
1977 - 1977                     9
1974 - 1974                     9
1986 - 1986                     9
1940                            9
1975 - 1975                     9
Siglo XIX                       8
1978 - 1978                     8
1939                            8
1670/1670                       8
1770/1830                       8
1735/1740                       8
1640/1660                       8
1938                            8
1870/1900                       8
1982 - 1982                     7
1924                            7
1650/1700                       7
1740/1760                       7
1928                            7
1750/1750                       7
1700/1700                       7
1875                            6
1941                            6
0                               6
1942                            6
1926                            6
1903                            6
1550/1550                       6
1948                            6
1949                            6
1630/1631                       6
1730/1740                       6
1916                            5
1870/1880                       5
1946                            5
1919                            5
1865                            5
1953                            5
1935                            5
1937                            5
1956                            5
1911                            5
1913                            5
1925                            5
1864                            5
1918                            5
1670/1700                       5
1701/1750                       5
ca. 1700                        5
1857                            5
1930                            5
1980 - 1980                     5
1864/1867                       5
1790/1800                       5
1801/1850                       5
1701/1730                       5
1944                            4
ca. 1930                        4
1898                            4
ca. 1945                        4
1945                            4
ca. 1780                        4
1979 - 1979                     4
1879                            4
1873                            4
1968/1970                       4
1700/1800                       4
1834                            4
1770                            4
1760                            4
1470/1500                       4
1970                            4
1775/1775                       4
1910                            4
ca. 1625                        4
1884                            4
1883                            4
1840/1840                       4
1610/1610                       4
1874                            4
1917                            4
1932                            4
1951                            4
1862                            4
1847/1851                       4
1952                            4
1934                            4
1927                            4
1954                            3
1973 - 1973                     3
1909                            3
1876                            3
1936                            3
1538/1540                       3
1610/1614                       3
1814                            3
1900                            3
ca. 1750                        3
1869                            3
ca. 1948                        3
ca. 1940                        3
1866                            3
1861/1861                       3
1970 - 1970                     3
Ca. 1420                        3
1828                            3
1907                            3
1915                            3
1801/1830                       3
1680/1680                       3
1885                            3
1776                            3
1590/1590                       3
1570/1570                       3
1815/1815                       3
1906                            3
ca. 1913                        3
Siglo XX                        3
Ca. 1780                        3
1754                            3
1729                            3
1854                            3
1601/1650                       3
1760/1780                       3
1851                            3
1877                            3
1610                            3
1660/1660                       3
1820/1820                       3
1914                            2
1771                            2
Ca. 1550                        2
1890                            2
1972 - 1972                     2
1893                            2
1908                            2
1758/1758                       2
ca. 1920                        2
1889                            2
1852                            2
1487/1487                       2
1850                            2
1477                            2
1912                            2
ca. 1960                        2
1750                            2
1500/1500                       2
ca. 1760                        2
1730/1760                       2
1823                            2
1845/1846                       2
ca. 1775                        2
ca. 1947                        2
ca. 1944                        2
ca. 1954                        2
ca. 1730                        2
ca. 1929                        2
1780                            2
ca. 1740                        2
ca. 1860                        2
1642/1644                       2
1797/1797                       2
1762                            2
1797                            2
ca. 1925                        2
1880                            2
1652                            2
1997                            2
1717                            2
1835                            2
1700/1750                       2
1723                            2
1617/1618                       2
1832                            2
1850/1889                       2
1740                            2
1630/1636                       2
1400/1400                       2
1819                            2
1697                            2
1868/1868                       2
1870/1930                       2
1747/1759                       2
1760/1760                       2
1825/1825                       2
1955                            2
1958                            2
ca.1610                         2
1500/1540                       2
1769                            2
1665                            2
ca. 1825                        2
1809                            2
1811/1812                       2
1540/1540                       2
1630                            2
1640/1640                       2
1751/1800                       2
1846                            2
1612                            2
1699                            2
1530/1540                       2
1745/1750                       2
1905                            2
1747                            2
1620/1630                       2
1655                            2
1848                            2
1855                            2
ca. 1910                        2
1847                            2
1618/1618                       2
1863                            2
1888                            2
1839                            2
1750/1780                       2
1730/1730                       2
1814/1814                       2
1560/1560                       2
1783                            2
1780/1780                       2
1830                            2
1720/1730                       2
1813                            2
Ca. 1720                        2
1526/1528                       2
1770/1770                       2
1933                            2
2004                            2
c. 1770                         2
1897                            2
1931                            2
Siglos XVI - XVII               1
1790                            1
Primer tercio del siglo XIX     1
1578                            1
1568/1568                       1
1732                            1
1788/1789                       1
1560/1650                       1
1769/1769                       1
Ca. 1640                        1
1795                            1
1886                            1
1920                            1
1964 - 1964                     1
ca.1918                         1
1730                            1
ca.1947                         1
1948/1948                       1
5 de julio de 1929              1
1998                            1
1350/1350                       1
1836/1850                       1
1668                            1
1580/1585                       1
1800/1850                       1
1880/1900                       1
1757/1757                       1
1564/1569                       1
1858                            1
1894                            1
1887                            1
2011                            1
1625/1632                       1
Ca. 1770                        1
1692                            1
Ca. 1800                        1
1594                            1
1550/1600                       1
1570/1600                       1
1860/1870                       1
1806/1808                       1
1645/1650                       1
1585/1590                       1
2019                            1
1574/1574                       1
1860/1878                       1
1777                            1
1605/1620                       1
1870                            1
1602                            1
1650                            1
1508/1510                       1
1537/1570                       1
1401/1430                       1
1871                            1
1555/1559                       1
1821                            1
1737                            1
1635/1640                       1
1826/1826                       1
1831/1847                       1
ca.1620                         1
Early 18th cent.                1
1827                            1
1585/1585                       1
1730/1732                       1
1770/1797                       1
1736/1738                       1
1867/1867                       1
1430/1450                       1
1764                            1
1551/1600                       1
1638/1638                       1
1650/1662                       1
1770/1775                       1
1771/1792                       1
1659/1659                       1
1780/1808                       1
1773/1774                       1
1370/1370                       1
1680/1689                       1
1365/1370                       1
1626/1626                       1
1750/1790                       1
1653                            1
1611                            1
1896                            1
1869/1869                       1
1800                            1
2006                            1
1524/1524                       1
1480/1490                       1
1750/1760                       1
1735/1738                       1
1588                            1
1651/1651                       1
1658/1658                       1
1555/1660                       1
1740/1740                       1
1701/1724                       1
1505/1508                       1
1760/1761                       1
1850/1881                       1
1633                            1
1832/1832                       1
1507/1507                       1
1891                            1
1855 - 1856                     1
ca. 1653 - 1655                 1
ca. 1771                        1
ca. 1612                        1
1450/1480                       1
22 de mayo de 1833              1
1782                            1
1759                            1
1720                            1
1651                            1
1760/1763                       1
1778                            1
1543/1544                       1
1793                            1
1670/1872                       1
1674                            1
1502/1504                       1
1841/1841                       1
1739/1740                       1
1798/1800                       1
1520                            1
1850/1879                       1
1560/1590                       1
1601/1625                       1
1770/1793                       1
1878                            1
1601/1630                       1
1694                            1
1790/1790                       1
S. XVIII                        1
1638/1642                       1
1870/1905                       1
1670/1710                       1
1912/1912                       1
1500/1530                       1
1921/1921                       1
1490/1495                       1
1911/1911                       1
1600/1620                       1
1850/1899                       1
1480/1510                       1
1823/1833                       1
1501/1512                       1
1634/1634                       1
1645/1649                       1
1866/1866                       1
1705/1705                       1
1780/1790                       1
1860/1860                       1
1885/1885                       1
1685/1685                       1
1500/1510                       1
1501/1530                       1
1855/1855                       1
1880/1880                       1
1661                            1
1783/1783                       1
1600/1610                       1
1450/1450                       1
1631/1632                       1
1625/1630                       1
1828/1828                       1
1720/1720                       1
1695                            1
1627/1632                       1
1810/1810                       1
1460/1480                       1
1901/1904                       1
1910/1910                       1
1667/1670                       1
1900/1900                       1
27 de Mayo de 1835              1
1918/1918                       1
1671/1671                       1
1857/1858                       1
1626                            1
1706                            1
1690/1690                       1
1616/1616                       1
1475/1500                       1
1647/1647                       1
1627/1628                       1
1756/1756                       1
1470                            1
1500/1550                       1
1781                            1
1892                            1
1743/1760                       1
1589/1589                       1
1817/1817                       1
23 de septiembre de 1910        1
1700/1749                       1
1860                            1
1520/1546                       1
1538/1538                       1
1631/1650                       1
1670/1790                       1
1530/1535                       1
1899/1901                       1
1810                            1
1665/1665                       1
1817/1818                       1
1610/1650                       1
1964                            1
1784                            1
Posclásico 900 a.C-1521 b.C     1
1814/1842                       1
1523/1525                       1
1971                            1
1780/1781                       1
1848/1848                       1
1700                            1
1660/1665                       1
1548/1548                       1
1600/1600                       1
1770/1780                       1
1630/1630                       1
1785                            1
1778/1778                       1
1815/1833                       1
1687/1715                       1
1907 - 1909                     1
1973                            1
ca. 1931                        1
1944-1945                       1
1977                            1
1881/1881                       1
1854/1854                       1
1696/1700                       1
1890/1900                       1
1580/1580                       1
1851/1900                       1
400 a. C.-300 a.C.              1
1707/1730                       1
1730/1770                       1
1715/1725                       1
1368/1644                       1
ca. 1874                        1
1536/1542                       1
1748/1750                       1
1771/1771                       1
1350/1370                       1
Siglos I al III                 1
1625/1625                       1
1880/1890                       1
1761                            1
1822/1822                       1
1675/1682                       1
1370/1400                       1
1831/1834                       1
1533/1533                       1
1601                            1
ca. 1933-1934                   1
1630/1640                       1
1630/1635                       1
1801 - 1832                     1
1853 - 1855                     1
1667                            1
1838/1838                       1
1849                            1
1554/1554                       1
1540/1550                       1
1510/1540                       1
ca.1769                         1
ca. 1758 - 1765                 1
1855-1858 - 1855-1859           1
1853                            1
1868                            1
ca. 1690                        1
1959                            1
2007                            1
Ca. 1950                        1
ca. 1942-1945                   1
1923                            1
1952-10-13                      1
1856                            1
ca. 1858                        1
1775                            1
ca. 1943                        1
ca. 1928                        1
1609 - 1610                     1
ca. 1717                        1
ca. 1769                        1
1522/1522                       1
1490/1490                       1
1508/1508                       1
1695/1695                       1
1751/1751                       1
1768                            1
1822                            1
1622/1625                       1
1705/1714                       1
1587/1596                       1
1899                            1
ca.1940                         1
1841                            1
ca. 1955                        1
1969                            1
ca. 1908                        1
1640                            1
ca.1921                         1
1690                            1
ca. 1927-1929                   1
1919/1919                       1
2000                            1
1946/1946                       1
ca.1700                         1
ca. 1871                        1
1746                            1
ca. 1865                        1
ca. 1953                        1
Ca. 1922                        1
ca. 1770                        1
1774                            1
1921                            1
ca.1960                         1
1966                            1
1987/1987                       1
ca 1938                         1
ca. 1909                        1
1967-1968                       1
ca. 1948-50                     1
ca 1690                         1
ca. 1938                        1
ca. 1710                        1
ca. 1950                        1
ca. 1770, -1760                 1
1621                            1
1974/1974                       1

In [30]:
def parse_date(text):
    if not isinstance(text, str):
        return np.nan, np.nan, False

    text = text.lower().strip()
    estimated = False

    if "ca" in text or "c." in text:
        estimated = True

    is_bc = "a.c" in text or "a. c" in text or "bc" in text


    match = re.search(r"siglo\s+([ivxlcdm]+)", text)
    if match:
        roman = match.group(1)
        roman_map = {'i':1,'v':5,'x':10,'l':50,'c':100,'d':500,'m':1000}

        def roman_to_int(s):
            total, prev = 0, 0
            for char in reversed(s):
                val = roman_map[char]
                if val < prev:
                    total -= val
                else:
                    total += val
                prev = val
            return total

        century = roman_to_int(roman)
        start = (century - 1) * 100
        end = century * 100

        return start, end, True


    nums = re.findall(r"\d{3,4}", text)

    if not nums:
        return np.nan, np.nan, estimated

    nums = [int(n) for n in nums]

    if is_bc:
        nums = [-n for n in nums]


    start = min(nums)
    end = max(nums)

    if len(nums) == 1:
        return start, start, estimated

    return start, end, estimated

In [31]:
df1[["year_start", "year_end", "estimated"]] = df1["date"].apply(
    lambda x: pd.Series(parse_date(x))
)

In [32]:
print(df1['year_end'].value_counts().to_string())

year_end
 1800.0    95
 1700.0    42
 1000.0    41
 1900.0    41
 1850.0    28
 1830.0    26
 1950.0    23
 1730.0    22
 1750.0    22
 1600.0    20
 1740.0    20
 1976.0    19
 1760.0    19
 1650.0    18
 1780.0    17
 1860.0    15
 1984.0    14
 1940.0    13
 1947.0    12
 1922.0    12
 1660.0    12
 1770.0    12
 1948.0    11
 1970.0    11
 1985.0    11
 1930.0    11
 1610.0    11
 1540.0    10
 1550.0    10
 1943.0    10
 1977.0    10
 1945.0    10
 1938.0    10
 1974.0    10
 2018.0    10
 1775.0     9
 1670.0     9
 1986.0     9
 1975.0     9
 1926.0     8
 1880.0     8
 1928.0     8
 1982.0     8
 1939.0     8
 1925.0     8
 1978.0     8
 1500.0     8
 1910.0     8
 1913.0     8
 1851.0     7
 1630.0     7
 1918.0     7
 1924.0     7
 1625.0     7
 1911.0     6
 1865.0     6
 1953.0     6
 1949.0     6
 1942.0     6
 1919.0     6
 1903.0     6
 1946.0     6
 1640.0     6
 1875.0     6
 1631.0     6
 1867.0     6
 1941.0     6
 1944.0     6
 1857.0     5
 1937.0     5
 1929.0     5
 1935.0     5
 1879.0     5
 1956.0     5
 1909.0     5
 1814.0     5
 1840.0     5
 1769.0     5
 1790.0     5
 1834.0     5
 1590.0     5
 1797.0     5
 1980.0     5
 1874.0     5
 1864.0     5
 1951.0     5
 1952.0     5
 1934.0     5
 1954.0     5
 1916.0     5
 1927.0     4
 1932.0     4
 1979.0     4
 1832.0     4
 1825.0     4
 1917.0     4
 1862.0     4
 1873.0     4
 1866.0     4
 1665.0     4
 1846.0     4
 1690.0     4
 1570.0     4
 1854.0     4
 1720.0     4
 1884.0     4
 1883.0     4
 1771.0     4
 1828.0     4
 1855.0     4
 1889.0     4
 1885.0     4
 1680.0     4
 2000.0     4
 1618.0     4
 1869.0     4
 1898.0     4
 1960.0     4
 1973.0     4
 1620.0     3
 1776.0     3
 1370.0     3
 1400.0     3
 1420.0     3
 1931.0     3
 1906.0     3
 1921.0     3
 1820.0     3
 1480.0     3
 1868.0     3
 1754.0     3
 1870.0     3
 1717.0     3
 1759.0     3
 1848.0     3
 1632.0     3
 1858.0     3
 1912.0     3
 1847.0     3
 1614.0     3
 1729.0     3
 1644.0     3
 1861.0     3
 1655.0     3
 1877.0     3
 1612.0     3
 1833.0     3
 1510.0     3
 1907.0     3
 1783.0     3
 1835.0     3
 1876.0     3
 1815.0     3
 1915.0     3
 1920.0     3
 1955.0     3
 1905.0     3
 1908.0     3
 1936.0     3
 1890.0     3
 1899.0     2
 1914.0     2
 1971.0     2
 1893.0     2
 1997.0     2
 1958.0     2
 2004.0     2
 1966.0     2
 1933.0     2
 1819.0     2
 1697.0     2
 1781.0     2
 1839.0     2
 1450.0     2
 1699.0     2
 1723.0     2
 1810.0     2
 1652.0     2
 1508.0     2
 1651.0     2
 1747.0     2
 1585.0     2
 1813.0     2
 1528.0     2
 1871.0     2
 1487.0     2
 1530.0     2
 1774.0     2
 1710.0     2
 1762.0     2
 1714.0     2
 1695.0     2
 1793.0     2
 1626.0     2
 1761.0     2
 1812.0     2
 1822.0     2
 1856.0     2
 1732.0     2
 1758.0     2
 1477.0     2
 1901.0     2
 1972.0     2
 1490.0     2
 1823.0     2
 1778.0     2
 1888.0     2
 1841.0     2
 1897.0     2
 1964.0     2
 1636.0     2
 1878.0     2
 1809.0     2
 1808.0     2
 1495.0     2
 1560.0     2
 1881.0     2
 1863.0     2
 1738.0     2
 1852.0     2
 1887.0     1
 2011.0     1
 1821.0     1
 1737.0     1
 1894.0     1
 1520.0     1
 1544.0     1
 1554.0     1
 1849.0     1
 1611.0     1
 1896.0     1
 1891.0     1
 1430.0     1
 1559.0     1
 1872.0     1
 1504.0     1
 1674.0     1
 1763.0     1
 1524.0     1
 2006.0     1
 1826.0     1
 1653.0     1
 1682.0     1
 1838.0     1
 1692.0     1
 1578.0     1
 1522.0     1
 1533.0     1
 1789.0     1
 1836.0     1
 1623.0     1
 1568.0     1
 1902.0     1
 1957.0     1
 1895.0     1
 1827.0     1
 1983.0     1
 1635.0     1
 1667.0     1
 1752.0     1
 1768.0     1
 1601.0     1
 1751.0     1
 1596.0     1
 1542.0     1
 1616.0     1
 1647.0     1
 1628.0     1
 1756.0     1
 1470.0     1
 1706.0     1
 1671.0     1
 1784.0     1
 1569.0     1
 1757.0     1
 1661.0     1
 1685.0     1
 1705.0     1
 1507.0     1
 1633.0     1
 1659.0     1
 1638.0     1
 1662.0     1
 1792.0     1
 1694.0     1
 1642.0     1
 1724.0     1
 1588.0     1
 1782.0     1
 1859.0     1
 1853.0     1
 1602.0     1
 1777.0     1
 1574.0     1
 1668.0     1
 1765.0     1
 1350.0     1
 1594.0     1
 2019.0     1
 1689.0     1
 1764.0     1
 1658.0     1
 1535.0     1
 1892.0     1
 1818.0     1
 1886.0     1
 1538.0     1
 1546.0     1
 1749.0     1
 1817.0     1
 1715.0     1
 1785.0     1
 1548.0     1
 1904.0     1
 1649.0     1
 1634.0     1
 1512.0     1
 1589.0     1
-300.0      1
 1580.0     1
-900.0      1
 2010.0     1
 1725.0     1
 1525.0     1
 1842.0     1
 1923.0     1
 2007.0     1
 1959.0     1
 2012.0     1
 1969.0     1
 1746.0     1
 1837.0     1
 1621.0     1
 1968.0     1
 1987.0     1
 1998.0     1
 1795.0     1

### Sexo

In [33]:
print(df1['artist_sex'].value_counts().to_string())

artist_sex
Male         136
Masculino    119
Female        10

In [34]:
df1['artist_sex'] = df1['artist_sex'].replace({
    'Masculino': 'Male',
    'Femenino': 'Female'
})

In [35]:
df1['artist_sex'].value_counts()

artist_sex
Male      255
Female     10
Name: count, dtype: int64

### Technique

In [36]:
df1['technique'].value_counts()

technique
Óleo sobre lienzo                                                                                                 261
Óleo sobre tela                                                                                                   160
Oil on canvas                                                                                                      82
Óleo sobre tabla                                                                                                   71
canvas                                                                                                             53
                                                                                                                 ...
Óleo y temple sobre tabla.                                                                                          1
Temple y oro sobre tabla. Marco de madera tallada y esgrafiada, con policromía y con aplicación de hoja de oro      1
Óleo sobre lámina de cobre. Marco de madera tallada con aplicación de hoja de oro                                   1
Bronce con pátina negra, dorada y café                                                                              1
Photography colored with oil by Frida Kahlo                                                                         1
Name: count, Length: 367, dtype: int64

In [37]:
def normalize_text(text):
    if not isinstance(text, str):
        return text
    
    text = text.lower().strip()

    replacements = {
        "á":"a","é":"e","í":"i","ó":"o","ú":"u","ñ":"n"
    }
    for k,v in replacements.items():
        text = text.replace(k,v)
    
    return text

In [38]:
TECHNIQUE_MAP = {
    "oleo": "oleo",
    "oil": "oleo",
    "acrílico": "acrilico",
    "acrilico": "acrilico",
    "acuarela": "acuarela",
    "watercolor": "acuarela",
    "gouache": "gouache",
    "tinta": "tinta",
    "grafito": "grafito",
    "pastel": "pastel",
    "litografia": "litografia",
    "serigrafia": "serigrafia",
    "temple": "temple"
}

SUPPORT_MAP = {
    "lienzo": "lienzo",
    "canvas": "lienzo",
    "tela": "tela",
    "papel": "papel",
    "carton": "carton",
    "madera": "madera",
    "tabla": "madera",
    "cobre": "metal",
    "zinc": "metal",
    "metal": "metal",
    "vidrio": "vidrio",
    "marfil": "marfil"
}

In [39]:
def extract_technique_support(text):
    if not isinstance(text, str):
        return None, None
    
    text = normalize_text(text)
    
    technique = None
    support = None
    
    for key in TECHNIQUE_MAP:
        if key in text:
            technique = TECHNIQUE_MAP[key]
            break
    
    for key in SUPPORT_MAP:
        if key in text:
            support = SUPPORT_MAP[key]
            break
    
    return technique, support

In [40]:
df1[["technique_clean", "support"]] = df1["technique"].apply(
    lambda x: pd.Series(extract_technique_support(x))
)

In [41]:
df1['support'].value_counts()

support
lienzo    435
tela      212
madera    209
papel      90
metal      76
marfil     26
carton     23
vidrio     13
Name: count, dtype: int64

In [42]:
df1['technique_clean'].value_counts()

technique_clean
oleo          851
acuarela       48
gouache        31
temple         27
tinta          26
pastel          7
litografia      2
grafito         2
Name: count, dtype: int64

### Theme

In [43]:
print(df1['theme'].value_counts().to_string())

theme
Paisaje                                                                                                                        69
Utensilios                                                                                                                     29
Herrería                                                                                                                       20
Numismática                                                                                                                    16
Virgen                                                                                                                         13
Santos                                                                                                                         10
batalla, caballo                                                                                                                8
Reliquias                                                                                                                       8
Génesis                                                                                                                         6
bodegón                                                                                                                         5
Paisaje, Nápoles, navíos,                                                                                                       4
Pintura de castas                                                                                                               4
La Piedad                                                                                                                       3
Virgen, Juan Bautista                                                                                                           3
utensilios                                                                                                                      3
Última Cena, discípulos                                                                                                         2
Ángel                                                                                                                           2
Madona, ángeles                                                                                                                 2
muelle, embarcaciones, edificación                                                                                              2
arquitectura, adulterio                                                                                                         2
aldea, festividades, campesinos                                                                                                 2
arco, geometría, abandono                                                                                                       2
Falerística                                                                                                                     2
Ángeles                                                                                                                         2
Ornamentos                                                                                                                      2
vereda, peregrinos, Calabria                                                                                                    2
campesinos, boda, juglares,                                                                                                     2
arquitectura                                                                                                                    2
Urban landscape                                                                                                                 1
Portrait                                                                                                                        1
Epifanía                                                                                                                        1
Iglesia, arquitectura, perro, púlpito,                                                                                          1
Eucaristía, discípulos                                                                                                          1
crucifixión, calvario,                                                                                                          1
León, meditación, Contrarreforma,                                                                                               1
Capa de armiño, Era Georgiana, Regencia                                                                                         1
lujuria, codicia, pecado, Torre de Babel                                                                                        1
Crucifixión, cáneo,                                                                                                             1
navío, naufragio, bandera                                                                                                       1
Caballos                                                                                                                        1
Natividad                                                                                                                       1
telares, hilanderos, tejedores                                                                                                  1
Agamenón, ejército, Eneas, Anquises                                                                                             1
ninfas, carcaj, perro, sátiros,                                                                                                 1
Schutenhut                                                                                                                      1
aristócratas                                                                                                                    1
El diluvio                                                                                                                      1
pureza                                                                                                                          1
ángeles                                                                                                                         1
cortesanos, carruajes, jinetes, caballos,                                                                                       1
Marquesa de la Selva Nevada                                                                                                     1
monja                                                                                                                           1
Crucifixión                                                                                                                     1
arquitectura, paisaje, Coliseo,                                                                                                 1
peñascos,                                                                                                                       1
mitología                                                                                                                       1
experiencia mística, resurrección,                                                                                              1
ruinas, vereda, animales de carga                                                                                               1
vela, interior, comerciante                                                                                                     1
arquitectura ciclópea                                                                                                           1
burguesía, puritano, gorguera,                                                                                                  1
calavera, buey, cordero                                                                                                         1
Infancia                                                                                                                        1
fundidora, metal, industria,                                                                                                    1
gorguera                                                                                                                        1
Still life                                                                                                                      1
veduta,                                                                                                                         1
Pasión, Gólgota, escalera, Calvario                                                                                             1
pastores, gansos                                                                                                                1
adulterio,                                                                                                                      1
Lamentación                                                                                                                     1
Falerísitca                                                                                                                     1
Santos Inocentes                                                                                                                1
mitología, pavorreal, perro,                                                                                                    1
río, ferry, pescadores, atmósfera                                                                                               1
campesinos, cerdo                                                                                                               1
sanación, milagros, ceguera                                                                                                     1
fuene, cántaros, perro                                                                                                          1
Babel, Génesis                                                                                                                  1
mula, buey                                                                                                                      1
Pirámides                                                                                                                       1
Diluvio Universal, Arca                                                                                                         1
Carnaval, soldado, burro, m´scara, glotonería, perro, bufón                                                                     1
armiño, drapeado                                                                                                                1
coral, litodendrum                                                                                                              1
invierno, calendario, morcilla, cerdo, gato                                                                                     1
imperialismo                                                                                                                    1
bahía napolitana, pescadores                                                                                                    1
tumba                                                                                                                           1
Gólgota, huesos,                                                                                                                1
Alegoría de los cinco sentidos                                                                                                  1
músicos, tambor, flauta                                                                                                         1
Paisaje, torre,                                                                                                                 1
cirugía, alquimista,                                                                                                            1
gabela,                                                                                                                         1
lechugilla, cuello escarolado, bigote,                                                                                          1
Armadura, militar,                                                                                                              1
Crucifixión,                                                                                                                    1
anciana, vela, avena,                                                                                                           1
aldea, molino, iglesia                                                                                                          1
suicidio                                                                                                                        1
pelícano                                                                                                                        1
puente, cañada                                                                                                                  1
Virgen, ángeles                                                                                                                 1
embarcaciones, pescadores,                                                                                                      1
molino, botes, río, puente                                                                                                      1
Paisaje, venecia                                                                                                                1
Paisaje, caballos, jinetes, ruinas                                                                                              1
cacería, jinetes, león, caballos                                                                                                1
La Visitación                                                                                                                   1
ángeles, carruaje, león, oso                                                                                                    1
Mendiga                                                                                                                         1
bacanal                                                                                                                         1
monasterio, perspectiva                                                                                                         1
apóstoles                                                                                                                       1
mula, buey, ángeles, pastores,                                                                                                  1
centurión, ángeles                                                                                                              1
anciana, zanahorias,                                                                                                            1
crucifixión,                                                                                                                    1
Plaza del Delfín, saltimbanqui, carruajes,                                                                                      1
Francia                                                                                                                         1
Reliquias, jesuitas                                                                                                             1
batalla, caballería, soldados                                                                                                   1
barril, vino, jarra, perro                                                                                                      1
La Iliada,                                                                                                                      1
La mejicana en chalupa                                                                                                          1
festividad, aldea                                                                                                               1
escena en una plaza, mono, buey, caballo, huevos                                                                                1
Los desposorios de la Virgen                                                                                                    1
estigmas                                                                                                                        1
Vendedora de carbón                                                                                                             1
caravana, carruajes,                                                                                                            1
Vanitas, cráneo, crucifijo, flores,reloj, monedas                                                                               1
ancianos, posada, aldea,                                                                                                        1
banquete                                                                                                                        1
Sagrada Familia                                                                                                                 1
arboleda, fuente,                                                                                                               1
La Transfiguración                                                                                                              1
costura,                                                                                                                        1
embacación, puente                                                                                                              1
pastores, ovejas, perros, ángeles                                                                                               1
ruinas                                                                                                                          1
Reliquias, Huida a Egipto                                                                                                       1
Paisaje, Vesubio                                                                                                                1
carruajes, jinetes, caballos, perros, expedición, asentamiento británico.                                                       1
encaje, joven                                                                                                                   1
Evangelio, huerto, ángel                                                                                                        1
burguesía                                                                                                                       1
anciano                                                                                                                         1
incendio, aduana                                                                                                                1
La Huida a Egipto                                                                                                               1
viajeros, montaña, puente,riachuelo                                                                                             1
Crucifijo, cortinaje, gorguera                                                                                                  1

In [44]:
THEME_CATEGORIES = {
    "religion": [
        "virgen", "cristo", "crucifixion", "calvario", "piedad",
        "santos", "angel", "natividad", "epifania",
        "eucaristia", "sagrada familia", "juicio final",
        "resurreccion", "iglesia", "biblia"
    ],
    
    "paisaje": [
        "paisaje", "rio", "montana", "bosque", "nubes",
        "mar", "costa", "volcan", "ruinas", "campo"
    ],
    
    "retrato": [
        "retrato", "autorretrato", "anciana", "anciano",
        "marquesa", "monja", "persona"
    ],
    
    "vida_cotidiana": [
        "campesinos", "boda", "festividad", "mercado",
        "trabajo", "cocina", "costura", "familia"
    ],
    
    "naturaleza_muerta": [
        "bodegon", "fruta", "comida", "mesa", "utensilios"
    ],
    
    "mitologia": [
        "mitologia", "troya", "agamenon", "ninfas", "satiros"
    ],
    
    "arquitectura": [
        "arquitectura", "edificio", "coliseo", "puente",
        "ciudad", "plaza", "torre"
    ],
    
    "animales": [
        "caballo", "perro", "vaca", "oveja", "leon",
        "aves", "animal"
    ],
    
    "guerra": [
        "batalla", "soldados", "ejercito", "caballeria"
    ]
}

In [45]:
def classify_theme(text):
    if not isinstance(text, str):
        return None
    
    text = normalize_text(text)
    
    matches = []
    
    for category, keywords in THEME_CATEGORIES.items():
        for word in keywords:
            if word in text:
                matches.append(category)
                break
    
    if not matches:
        return "otro"
    
    return list(set(matches))

In [46]:
df1["theme_tag"] = df1["theme"].apply(classify_theme)

In [47]:
df1['theme_tag'].value_counts()

theme_tag
otro                                  147
[paisaje]                              86
[religion]                             50
[naturaleza_muerta]                    37
[animales]                             11
[arquitectura]                          8
[animales, guerra]                      8
[paisaje, arquitectura]                 8
[vida_cotidiana]                        8
[retrato]                               6
[religion, paisaje]                     4
[retrato, arquitectura]                 2
[animales, paisaje]                     2
[mitologia]                             2
[mitologia, paisaje]                    2
[religion, animales]                    2
[animales, mitologia]                   2
[religion, animales, arquitectura]      1
[animales, arquitectura]                1
[mitologia, guerra]                     1
[retrato, paisaje]                      1
[religion, vida_cotidiana]              1
[guerra]                                1
[vida_cotidiana, arquitectura]          1
[vida_cotidiana, paisaje]               1
Name: count, dtype: int64

### Lugar

In [48]:
print(  df1['origin'].value_counts().to_string())

origin
Colección privada                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         71
Colección Privada                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         48
México                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    24
España                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    22
Museo Soumaya                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             20
Nueva España                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              16
Nueva España (México)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     12
Mexico                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     9
Europa                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     4
Valencia, España                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           4
Guatemala                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  3
Rusia                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      2
Gante, Flandes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             2
Flandes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2
Sevilla, España                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            2
Filipinas                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  2

In [49]:
def clean_origin_text(x):
    if not isinstance(x, str):
        return None
    
    x = x.strip()
    
    if len(x) > 100:
        return None
    
    return x

In [50]:
def extract_region_country(x):
    if not isinstance(x, str):
        return None, None
    
    parts = [p.strip() for p in x.split(",") if p.strip()]
    
    if len(parts) == 0:
        return None, None
    
    elif len(parts) == 1:
        return None, parts[0]
    
    else:
        return parts[-2], parts[-1]

In [51]:
def normalize_country(country):
    if not isinstance(country, str):
        return None
    
    country = country.lower()
    
    mapping = {
        "mexico": "México",
        "méxico": "México",
        "españa": "España",
        "spain": "España",
        "francia": "Francia",
        "france": "Francia",
        "italia": "Italia",
        "new york": "Estados Unidos",
        "usa": "Estados Unidos",
        "estados unidos": "Estados Unidos",
        "europa": "Europa",
        "nueva españa": "Nueva España",
        "nueva españa (méxico)": "Nueva España"
    }
    
    return mapping.get(country, country.capitalize())

In [52]:
def process_origin(df):
    df["origin"] = df["origin"].apply(clean_origin_text)
    
    regiones = []
    paises = []
    
    for val in df["origin"]:
        region, country = extract_region_country(val)
        
        region = region.strip() if isinstance(region, str) else None
        country = normalize_country(country)
        
        regiones.append(region)
        paises.append(country)
    
    df["region"] = regiones
    df["pais"] = paises
    
    return df

In [53]:
df1 = process_origin(df1)

In [54]:
def clean_nationality(text):
    if not isinstance(text, str):
        return None
    
    text = text.lower().strip()

    # eliminar ruido común
    text = text.split("born")[0]
    text = text.split(" or ")[0]
    text = text.split(" and ")[0]
    text = text.split(",")[0]

    text = text.strip()

    # diccionario de normalización
    mapping = {
        "italian": "italiano",
        "german": "alemán",
        "spanish": "español",
        "american": "estadounidense",
        "mexican": "mexicano",
        "hungarian": "húngaro",
    }

    return mapping.get(text, text)

In [55]:
df1["artist_nationality"] = df1["artist_nationality"].apply(clean_nationality)

In [56]:
print(df1['artist_nationality'].value_counts().to_string())

artist_nationality
mexicano          202
español            17
alemán             10
húngaro             1
estadounidense      1
italiano            1

## The Met

In [57]:
with open("data/the_metropolitan_museum_of_art/dataset.json", "r", encoding="utf-8") as f:
    met_data = json.load(f)

met = pd.DataFrame(met_data)

In [58]:
met.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1207 entries, 0 to 1206
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   objectID           1207 non-null   int64
 1   title              1207 non-null   object
 2   artist             1207 non-null   object
 3   artistNationality  1207 non-null   object
 4   objectDate         1207 non-null   object
 5   medium             1207 non-null   object
 6   dimensions         1207 non-null   object
 7   department         1207 non-null   object
 8   culture            1207 non-null   object
 9   country            1207 non-null   object
 10  classification     1207 non-null   object
 11  image              1207 non-null   object
 12  objectURL          1207 non-null   object
dtypes: int64(1), object(12)
memory usage: 122.7+ KB

In [59]:
met.head()

,objectID,title,artist,artistNationality,objectDate,medium,dimensions,department,culture,country,classification,image,objectURL
0,437056,Tommaso di Folco Portinari (1428–1501); Maria ...,Hans Memling,Netherlandish,ca. 1470,Oil on oak,"(.626, Tommaso) overall 17 3/8 x 13 1/4 in. (4...",European Paintings,,,Paintings,https://images.metmuseum.org/CRDImages/ep/orig...,https://www.metmuseum.org/art/collection/searc...
1,929079,Orchids and Rocks,Yi Ha-eung,Korean,1888,Hanging scroll; ink on silk,Image: 60 1/2 × 40 1/16 in. (153.7 × 101.8 cm)...,Asian Art,Korea,,Paintings,https://images.metmuseum.org/CRDImages/as/orig...,https://www.metmuseum.org/art/collection/searc...
2,764091,Our Lady of Valvanera,Unknown,,ca. 1770–80,Oil and gold on canvas,80 1/16 × 95 7/8 in. (203.4 × 243.5 cm),The American Wing,Peru (Cuzco),,,https://images.metmuseum.org/CRDImages/ad/orig...,https://www.metmuseum.org/art/collection/searc...
3,453250,Study of a Bird,Riza-yi 'Abbasi,Iranian,dated 1043 AH/1634 CE,"Ink, opaque watercolor, gold, and silver on paper",Overall:\r\n H. 4 1/4 in. (10.8 cm...,Islamic Art,,Iran,Codices,https://images.metmuseum.org/CRDImages/is/orig...,https://www.metmuseum.org/art/collection/searc...
4,764095,"Christ Carrying the Cross, called ""The Lord of...",Unknown,,ca. 1770–75,Oil and gold on canvas,65 × 48 in. (165.1 × 121.9 cm),The American Wing,Peru (Cuzco),,,https://images.metmuseum.org/CRDImages/ad/orig...,https://www.metmuseum.org/art/collection/searc...

In [60]:
def normalize_missing(df):
    df = df.replace({
        None: np.nan,
        "": np.nan,
        " ": np.nan
    })
    return df

In [61]:
normalize_missing(met)

,objectID,title,artist,artistNationality,objectDate,medium,dimensions,department,culture,country,classification,image,objectURL
0,437056,Tommaso di Folco Portinari (1428–1501); Maria ...,Hans Memling,Netherlandish,ca. 1470,Oil on oak,"(.626, Tommaso) overall 17 3/8 x 13 1/4 in. (4...",European Paintings,NaN,NaN,Paintings,https://images.metmuseum.org/CRDImages/ep/orig...,https://www.metmuseum.org/art/collection/searc...
1,929079,Orchids and Rocks,Yi Ha-eung,Korean,1888,Hanging scroll; ink on silk,Image: 60 1/2 × 40 1/16 in. (153.7 × 101.8 cm)...,Asian Art,Korea,NaN,Paintings,https://images.metmuseum.org/CRDImages/as/orig...,https://www.metmuseum.org/art/collection/searc...
2,764091,Our Lady of Valvanera,Unknown,NaN,ca. 1770–80,Oil and gold on canvas,80 1/16 × 95 7/8 in. (203.4 × 243.5 cm),The American Wing,Peru (Cuzco),NaN,NaN,https://images.metmuseum.org/CRDImages/ad/orig...,https://www.metmuseum.org/art/collection/searc...
3,453250,Study of a Bird,Riza-yi 'Abbasi,Iranian,dated 1043 AH/1634 CE,"Ink, opaque watercolor, gold, and silver on paper",Overall:\r\n H. 4 1/4 in. (10.8 cm...,Islamic Art,NaN,Iran,Codices,https://images.metmuseum.org/CRDImages/is/orig...,https://www.metmuseum.org/art/collection/searc...
4,764095,"Christ Carrying the Cross, called ""The Lord of...",Unknown,NaN,ca. 1770–75,Oil and gold on canvas,65 × 48 in. (165.1 × 121.9 cm),The American Wing,Peru (Cuzco),NaN,NaN,https://images.metmuseum.org/CRDImages/ad/orig...,https://www.metmuseum.org/art/collection/searc...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1202,53213,Herd Boy with Ox,Kano Masanobu 狩野正信,Japanese,late 15th century,Folding fan mounted as a hanging scroll; ink a...,Image: 8 7/8 × 18 1/2 in. (22.5 × 47 cm)\r\nOv...,Asian Art,Japan,NaN,Paintings,https://images.metmuseum.org/CRDImages/as/orig...,https://www.metmuseum.org/art/collection/searc...
1203,203915,Seated Faun,"Andrea Briosco, called Riccio",Italian,ca. 1540–50,Bronze,Overall (confirmed): 11 1/4 × 7 × 7 1/2 in. (2...,European Sculpture and Decorative Arts,NaN,NaN,Sculpture-Bronze,https://images.metmuseum.org/CRDImages/es/orig...,https://www.metmuseum.org/art/collection/searc...
1204,436523,The Adoration of the Magi,Hugo van der Goes,Netherlandish,NaN,Oil on wood,29 1/8 x 25 5/8 in. (74 x 65.1 cm),European Paintings,NaN,NaN,Paintings,https://images.metmuseum.org/CRDImages/ep/orig...,https://www.metmuseum.org/art/collection/searc...
1205,436553,A City on a Rock,Goya,Spanish,NaN,Oil on canvas,33 × 41 in. (83.8 × 104.1 cm),European Paintings,NaN,NaN,Paintings,https://images.metmuseum.org/CRDImages/ep/orig...,https://www.metmuseum.org/art/collection/searc...
1206,436670,"Edward VI (1537–1553), When Duke of Cornwall",Hans Holbein the Younger,German,ca. 1545; reworked 1547 or later,Oil and gold on oak,Diameter 12 3/4 in. (32.4 cm),European Paintings,NaN,NaN,Paintings,https://images.metmuseum.org/CRDImages/ep/orig...,https://www.metmuseum.org/art/collection/searc...

In [62]:
def transform_met(df):
    return pd.DataFrame({
        "title": df["title"],
        "artist": df["artist"],
        "description": np.nan,

        "image_path": df["image"],
        "dimensions": df["dimensions"],

        "artist_nationality": df["artistNationality"],
        "artist_birthplace": np.nan,
        "artist_deathplace": np.nan,
        "artist_sex": np.nan,

        "type": df["classification"],
        "type_norm": df["classification"],

        "technique": df["medium"],

        "theme": np.nan,
        "genre": np.nan,
        "keywords": np.nan,

        "origin": df["country"],
        "pais": df["country"],

        "date": df["objectDate"],
        "museum": "MET"
    })

## Normalizar Valores

### Imágenes

In [63]:
def limpiar_nombre(nombre):
    if not isinstance(nombre, str):
        return "unknown"

    nombre = unicodedata.normalize('NFKD', nombre)
    nombre = nombre.encode('ascii', 'ignore').decode('ascii')

    nombre = nombre.lower()
    nombre = nombre.replace(" ", "_")

    nombre = re.sub(r'[^a-z0-9_]', '', nombre)
    nombre = re.sub(r'_+', '_', nombre)  # 👈 evita ___

    return nombre.strip("_")

def generar_nombre_imagen(row):
    titulo = limpiar_nombre(row["title"])
    object_id = row["objectID"]

    return f"{titulo}_{object_id}.jpg"


def generar_ruta_imagen(row):
    nombre = generar_nombre_imagen(row)
    return f"data/the_metropolitan_museum_of_art/_images/{nombre}"

### Fecha

In [64]:
def parse_dates_met(df):
    parsed = df["date"].apply(lambda x: pd.Series(parse_date(x)))
    parsed.columns = ["year_start", "year_end", "estimated"]

    return pd.concat([df, parsed], axis=1)

### Dimensiones

In [65]:

def parse_dimensions_met(text):
    if not isinstance(text, str):
        return np.nan, np.nan, np.nan

    match = re.search(r"\(([\d\.]+)\s*[×x]\s*([\d\.]+)\s*cm\)", text)

    if match:
        height = float(match.group(1))
        width = float(match.group(2))
        return width, height, np.nan

    return np.nan, np.nan, np.nan

### Tipo

In [66]:

def normalize_type_es(text):
    if not isinstance(text, str) or text.strip() == "":
        return np.nan
    
    text = text.lower()

    if "painting" in text or "oil" in text:
        return "pintura"

    if "drawing" in text or "pastel" in text:
        return "dibujo"

    if "print" in text or "etching" in text or "engraving" in text:
        return "impresión"

    if "photograph" in text:
        return "fotografía"
    
    if any(x in text for x in [
        "sculpture", "stone", "marble", "jade", "ivories", "wood"
    ]):
        return "escultura"

    if "textile" in text or "tapestry" in text or "rug" in text:
        return "textil"
    
    if any(x in text for x in [
        "book", "manuscript", "codices", "calligraphy", "illustrated"
    ]):
        return "libro"

    if any(x in text for x in [
        "ceramic", "glass", "metal", "jewelry", "horology",
        "weapon", "armor", "instrument", "shell", "lacquer"
    ]):
        return "objeto"

    return "otro"

### Lugar

In [74]:

def normalize_pais(text):
    if not isinstance(text, str):
        return np.nan
    
    text = text.lower()

    if "mexico" in text:
        return "México"
    if "peru" in text:
        return "Perú"
    if "guatemala" in text:
        return "Guatemala"
    if "spain" in text:
        return "España"
    if "france" in text:
        return "Francia"
    if "italy" in text:
        return "Italia"
    if "germany" in text:
        return "Alemania"
    if "netherlands" in text:
        return "Países Bajos"
    if "japan" in text:
        return "Japón"
    if "china" in text:
        return "China"
    if "india" in text:
        return "India"
    if "iran" in text:
        return "Irán"
    if "egypt" in text:
        return "Egipto"
    if "united states" in text or "american" in text:
        return "Estados Unidos"
    if "afghanistan" in text:
        return "Afganistán"
    if "pakistan" in text:
        return "Pakistán"
    if "syria" in text:
        return "Siria"
    if "iraq" in text:
        return "Irak"
    if "england" in text or "united kingdom" in text:
        return "Reino Unido"
    if "belgium" in text:
        return "Bélgica"
    if "ethiopia" in text:
        return "Etiopía"
    if "solomon islands" in text:
        return "Islas Salomón"
    if "turkey" in text:
        return "Turquía"
    if "papua new guinea" in text:
        return "Papúa Nueva Guinea"
    if "nubia" in text:
        return "Nubia"
    if "new caledonia" in text:
        return "Nueva Caledonia"
    if "uzbekistan" in text:
        return "Uzbekistán"
    if "panama" in text:
        return "Panamá"
    if "costa rica" in text:
        return "Costa Rica"
    if "nepal" in text:
        return "Nepal"

    return "otro"

In [75]:

def clean_nationality(text):
    if not isinstance(text, str):
        return None
    
    text = text.lower().strip()

    # eliminar ruido común
    text = text.split("born")[0]
    text = text.split(" or ")[0]
    text = text.split(" and ")[0]
    text = text.split(",")[0]

    text = text.strip()

    # diccionario de normalización
    mapping = {
        "french": "francés",
        "italian": "italiano",
        "netherlandish": "neerlandés",
        "dutch": "neerlandés",
        "flemish": "flamenco",
        "german": "alemán",
        "british": "británico",
        "english": "británico",
        "spanish": "español",
        "american": "estadounidense",
        "mexican": "mexicano",
        "japanese": "japonés",
        "chinese": "chino",
        "korean": "coreano",
        "indian": "indio",
        "iranian": "iraní",
        "egyptian": "egipcio",
        "greek": "griego",
        "swiss": "suizo",
        "austrian": "austriaco",
        "danish": "danés",
        "norwegian": "noruego",
        "belgian": "belga",
        "bohemian": "bohemio",
        "ethiopian": "etíope",
        "guatemalan": "guatemalteco",
        "african": "africano",
        "khitan": "khitan",  # lo puedes dejar como histórico
        "northern european": "europeo"
    }

    return mapping.get(text, text)  # fallback: deja lo que no reconozca

### Técnica

In [76]:
def normalize_technique(text):
    if not isinstance(text, str):
        return None
    
    t = text.lower()

    if any(k in t for k in ["oil"]):
        return "óleo"
    if any(k in t for k in ["ink"]):
        return "tinta"
    if any(k in t for k in ["watercolor", "gouache"]):
        return "acuarela"
    if "tempera" in t:
        return "temple"
    if "pastel" in t:
        return "pastel"
    if any(k in t for k in ["etching", "engraving", "mezzotint", "drypoint"]):
        return "grabado"
    if "lithograph" in t:
        return "litografía"
    if any(k in t for k in ["photo", "print", "albumen"]):
        return "fotografía"
    if any(k in t for k in ["ceramic", "porcelain", "earthenware"]):
        return "cerámica"
    if any(k in t for k in ["textile", "silk", "wool"]):
        return "textil"
    
    return "otro"

In [77]:
def normalize_support(text):
    if not isinstance(text, str):
        return None
    
    t = text.lower()

    if "canvas" in t:
        return "lienzo"
    if any(k in t for k in ["paper", "cardboard"]):
        return "papel"
    if any(k in t for k in ["wood", "panel", "oak", "walnut", 'oak', 'linden', 'spruce', 'walnut', 'pine', 'fir']):
        return "madera"
    if any(k in t for k in ["metal", "bronze", "copper", "silver", "gold", "brass", "steel"]):
        return "metal"
    if "silk" in t:
        return "seda"
    if "linen" in t:
        return "lino"
    if any(k in t for k in ["ceramic", "porcelain"]):
        return "cerámica"
    if any(k in t for k in ["stone", "marble", "alabaster"]):
        return "piedra"
    if "glass" in t:
        return "vidrio"
    if "ivory" in t:
        return "marfil"
    if "parchment" in t or "vellum" in t:
        return "pergamino"

    return "otro"

In [81]:

def split_technique(text):
    if not isinstance(text, str):
        return None, None
    
    text = text.lower()

    if " on " in text:
        parts = text.split(" on ")
        return parts[0], parts[1]

    return text, None
def clean_technique_met(df):
    split = df["technique"].apply(lambda x: pd.Series(split_technique(x)))
    split.columns = ["technique_raw", "support_raw"]

    df = pd.concat([df, split], axis=1)

    df["technique_clean"] = df["technique_raw"].apply(normalize_technique)
    df["support"] = df["support_raw"].apply(normalize_support)

    return df

### Pipeline

In [82]:


def clean_met_pipeline(df):
    df = transform_met(df)

    df = clean_strings(df)

    df = parse_dates_met(df)

    dims = df["dimensions"].apply(lambda x: pd.Series(parse_dimensions_met(x)))
    dims.columns = ["width_cm", "height_cm", "depth_cm"]

    df = pd.concat([df, dims], axis=1)

    df = clean_technique_met(df)

    df = df.replace(r"^\s*$", np.nan, regex=True)
    df["type_norm"] = df["type"].apply(normalize_type)
    df["pais"] = df["pais"].apply(normalize_pais)
    df["artist_nationality"] = df["artist_nationality"].apply(clean_nationality)

    return df

In [83]:
met = clean_met_pipeline(met)

C:\Users\roxan\AppData\Local\Temp\ipykernel_41300\2677936922.py:96: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return df.applymap(limpiar)

In [84]:
met.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1207 entries, 0 to 1206
Data columns (total 29 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               1207 non-null   object
 1   artist              938 non-null    object
 2   description         0 non-null      float64
 3   image_path          1207 non-null   object
 4   dimensions          1197 non-null   object
 5   artist_nationality  837 non-null    object
 6   artist_birthplace   0 non-null      float64
 7   artist_deathplace   0 non-null      float64
 8   artist_sex          0 non-null      float64
 9   type                1146 non-null   object
 10  type_norm           1146 non-null   object
 11  technique           1207 non-null   object
 12  theme               0 non-null      float64
 13  genre               0 non-null      float64
 14  keywords            0 non-null      float64
 15  origin              272 non-null    object
 16  pais                272 non-null    object
 17  date                1153 non-null   object
 18  museum              1207 non-null   object
 19  year_start          932 non-null    float64
 20  year_end            932 non-null    float64
 21  estimated           1207 non-null   bool
 22  width_cm            797 non-null    float64
 23  height_cm           797 non-null    float64
 24  depth_cm            0 non-null      float64
 25  technique_raw       1207 non-null   object
 26  support_raw         783 non-null    object
 27  technique_clean     1207 non-null   object
 28  support             783 non-null    object
dtypes: bool(1), float64(12), object(16)
memory usage: 265.3+ KB

In [85]:
met.loc[met['type_norm'] == 'otro', 'type'].unique()

array(['Codices', 'Glass-Stained', 'Prints', 'Enamels-Cloisonné', 'Glass',
       'Ceramics', 'Ceramics-Porcelain-Export',
       'Manuscripts and Illuminations', 'Ceramics-Porcelain', 'Jade',
       'Woodwork', 'Chordophone-Zither-struck-piano', 'Horology', 'Wood',
       'Woodwork-Furniture', 'Ceramics-Containers', 'Jewelry',
       'Ivories-Elephant', 'Mosaics', 'Calligraphy', 'Stone-Implements',
       'Woodwork-Lacquer', 'Ivories', 'Ceramics-Vessels',
       'Enamels-Champlevé', 'Wallpaper', 'Wood-Containers',
       'Faience-Cylinder Seals', 'Pastels & Oil Sketches on Paper',
       'Stone', 'Wood-Architectural', 'Bone', 'Miniatures',
       'Hide-Documents', 'Vases', 'Metal-Ornaments', 'Amber', 'Screens',
       'Ceramics-Tiles', 'Ceramics-Pottery', 'Stone-Ornaments',
       'Illustrated Books', 'Medals', 'Ephemera', 'Shell-Ornaments',
       'Idiophone', 'Seals', 'Metalwork', 'Leatherwork',
       'Metalwork-Silver', 'Enamels-Painted', 'Metal', 'Lacquer', 'Books',
       'Knives', 'Shafted Weapons', 'Aerophone-Reed Vibrated-bagpipe',
       'Armor Parts-Cuirasses', 'Enamels', 'Ivories-Bone',
       'games or toys'], dtype=object)

In [86]:
met.loc[met['technique_clean'] == 'other', 'technique_raw'].unique()

array([], dtype=object)

In [87]:
met.loc[met['pais'] == 'otro', 'origin'].unique()

array([], dtype=object)

In [88]:
print(met['artist_nationality'].value_counts().to_string())

artist_nationality
francés           175
italiano          154
neerlandés        151
japonés            63
británico          61
alemán             54
chino              43
iraní              37
estadounidense     24
español            23
indio              10
flamenco            8
austriaco           6
griego              5
suizo               5
bohemio             3
noruego             3
belga               2
mexicano            2
coreano             1
danés               1
egipcio             1
europeo             1
guatemalteco        1
etíope              1
africano            1
khitan              1

In [89]:
print(met['pais'].value_counts().to_string())

pais
Irán                  66
India                 39
Francia               25
Egipto                25
México                21
Perú                  18
Guatemala             13
Alemania               7
Etiopía                6
Siria                  6
Reino Unido            6
Italia                 5
Turquía                5
Estados Unidos         4
Nepal                  4
Pakistán               3
España                 3
Afganistán             3
Panamá                 2
Países Bajos           2
Nueva Caledonia        2
Islas Salomón          1
Nubia                  1
Papúa Nueva Guinea     1
Irak                   1
Uzbekistán             1
Costa Rica             1
Bélgica                1

## Merge

In [90]:
# cols_final = [
#     "title", "artist", "description", "image_path", "dimensions",
#     "artist_deathplace", "artist_birthplace", "artist_nationality", "artist_sex",
#     "keywords", "type", "type_norm", "technique", "theme", "genre",
#     "origin", "date", "museum",
#     "width_cm", "height_cm", "depth_cm",
#     "year_start", "year_end", "estimated",
#     "technique_clean", "support", "theme_tag",
#     "region", "pais"
# ]

# met = met.reindex(columns=cols_final)

In [91]:
df1 = df1.rename(columns={"theme_tag": "theme"})

In [92]:
cols_final = [
    "title", "artist", "description", "image_path", "dimensions",
    "artist_deathplace", "artist_birthplace", "artist_nationality", "artist_sex",
    "keywords",
    
    "type_norm",
    "technique_clean", "support",
    "theme",
    "pais",
    
    "year_start", "year_end", "estimated",
    "width_cm", "height_cm", "depth_cm",
    
    "museum"
]

In [93]:
df1 = df1[cols_final]

In [94]:
met = met[cols_final]

In [95]:
df1 = df1.rename(columns={
    "type_norm": "type",
    "technique_clean": "technique",
    "pais": "country"
})

In [96]:
met = met.rename(columns={
    "type_norm": "type",
    "technique_clean": "technique",
    "pais": "country"
})

In [97]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1711 entries, ('FridaKahlo', np.int64(0)) to ('Arocena', np.int64(125))
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               1711 non-null   object
 1   artist              1711 non-null   object
 2   description         1184 non-null   object
 3   image_path          1711 non-null   object
 4   dimensions          1450 non-null   object
 5   artist_deathplace   182 non-null    object
 6   artist_birthplace   222 non-null    object
 7   artist_nationality  232 non-null    object
 8   artist_sex          265 non-null    object
 9   keywords            255 non-null    object
 10  type                1355 non-null   object
 11  technique           994 non-null    object
 12  support             1084 non-null   object
 13  theme               393 non-null    object
 14  theme               393 non-null    object
 15  country             252 non-null    object
 16  year_start          1499 non-null   float64
 17  year_end            1499 non-null   float64
 18  estimated           1711 non-null   bool
 19  width_cm            1412 non-null   float64
 20  height_cm           1396 non-null   float64
 21  depth_cm            279 non-null    float64
 22  museum              1711 non-null   object
dtypes: bool(1), float64(5), object(17)
memory usage: 340.5+ KB

In [98]:
df1 = df1.loc[:, ~df1.columns.duplicated()]

In [99]:
met.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1207 entries, 0 to 1206
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               1207 non-null   object
 1   artist              938 non-null    object
 2   description         0 non-null      float64
 3   image_path          1207 non-null   object
 4   dimensions          1197 non-null   object
 5   artist_deathplace   0 non-null      float64
 6   artist_birthplace   0 non-null      float64
 7   artist_nationality  837 non-null    object
 8   artist_sex          0 non-null      float64
 9   keywords            0 non-null      float64
 10  type                1146 non-null   object
 11  technique           1207 non-null   object
 12  support             783 non-null    object
 13  theme               0 non-null      float64
 14  country             272 non-null    object
 15  year_start          932 non-null    float64
 16  year_end            932 non-null    float64
 17  estimated           1207 non-null   bool
 18  width_cm            797 non-null    float64
 19  height_cm           797 non-null    float64
 20  depth_cm            0 non-null      float64
 21  museum              1207 non-null   object
dtypes: bool(1), float64(11), object(10)
memory usage: 199.3+ KB

In [100]:
df_final = pd.concat([df1, met], axis=0)

In [101]:
df_final

,title,artist,description,image_path,dimensions,artist_deathplace,artist_birthplace,artist_nationality,artist_sex,keywords,...,support,theme,country,year_start,year_end,estimated,width_cm,height_cm,depth_cm,museum
"(FridaKahlo, 0)","Matilde, Adriana, Frida y Cristina Kahlo",Guillermo Kahlo,"Desde niña, Frida estuvo cerca de la fotografí...",data/museo_frida_kahlo/images/matilde_adriana_...,NaN,"Mexico City, Mexico","Baden, Germany",alemán,Male,NaN,...,None,NaN,None,1916.0,1916.0,False,NaN,NaN,NaN,FridaKahlo
"(FridaKahlo, 1)",Retrato de Agustín M Olmedo,Unknown,"Retrato de Agustín M. Olmedo, ca. 1927. Óleo s...",data/museo_frida_kahlo/images/retrato_de_agust...,NaN,NaN,NaN,None,NaN,NaN,...,None,NaN,None,1927.0,1927.0,False,NaN,NaN,NaN,FridaKahlo
"(FridaKahlo, 2)",El marxismo dará salud a los enfermos,Frida Kahlo,El estado de ánimo de Frida Kahlo se evidencia...,data/museo_frida_kahlo/images/el_marxismo_dar_...,w600 x h760 mm (without frame),"Mexico City, Mexico","Mexico City, Mexico",mexicano,Female,NaN,...,None,NaN,México,1954.0,1954.0,False,60.0,76.0,NaN,FridaKahlo
"(FridaKahlo, 3)",Viva la vida,Frida Kahlo,"""Viva la vida"" es un cuadro muy importante, ya...",data/museo_frida_kahlo/images/viva_la_vida_bAG...,w720 x h520 mm (with frame),"Mexico City, Mexico","Mexico City, Mexico",mexicano,Female,NaN,...,None,NaN,None,1954.0,1954.0,False,72.0,52.0,NaN,FridaKahlo
"(FridaKahlo, 4)",Las apariencias engañan,Frida Kahlo,"Este dibujo no se conoció hasta 2007, dado que...",data/museo_frida_kahlo/images/las_apariencias_...,w297 x h298 mm (without frame),"Mexico City, Mexico","Mexico City, Mexico",mexicano,Female,NaN,...,None,NaN,None,1934.0,1934.0,False,29.7,29.8,NaN,FridaKahlo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1202,Herd Boy with Ox,Kano Masanobu 狩野正信,NaN,https://images.metmuseum.org/CRDImages/as/orig...,Image: 8 7/8 × 18 1/2 in. (22.5 × 47 cm)\r\nOv...,NaN,NaN,japonés,NaN,NaN,...,papel,NaN,NaN,NaN,NaN,False,47.0,22.5,NaN,MET
1203,Seated Faun,"Andrea Briosco, called Riccio",NaN,https://images.metmuseum.org/CRDImages/es/orig...,Overall (confirmed): 11 1/4 × 7 × 7 1/2 in. (2...,NaN,NaN,italiano,NaN,NaN,...,None,NaN,NaN,1540.0,1540.0,True,NaN,NaN,NaN,MET
1204,The Adoration of the Magi,Hugo van der Goes,NaN,https://images.metmuseum.org/CRDImages/ep/orig...,29 1/8 x 25 5/8 in. (74 x 65.1 cm),NaN,NaN,neerlandés,NaN,NaN,...,madera,NaN,NaN,NaN,NaN,False,65.1,74.0,NaN,MET
1205,A City on a Rock,Goya,NaN,https://images.metmuseum.org/CRDImages/ep/orig...,33 × 41 in. (83.8 × 104.1 cm),NaN,NaN,español,NaN,NaN,...,lienzo,NaN,NaN,NaN,NaN,False,104.1,83.8,NaN,MET
1206,"Edward VI (1537–1553), When Duke of Cornwall",Hans Holbein the Younger,NaN,https://images.metmuseum.org/CRDImages/ep/orig...,Diameter 12 3/4 in. (32.4 cm),NaN,NaN,alemán,NaN,NaN,...,madera,NaN,NaN,1545.0,1547.0,True,NaN,NaN,NaN,MET

In [102]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2918 entries, ('FridaKahlo', 0) to 1206
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               2918 non-null   object
 1   artist              2649 non-null   object
 2   description         1184 non-null   object
 3   image_path          2918 non-null   object
 4   dimensions          2647 non-null   object
 5   artist_deathplace   182 non-null    object
 6   artist_birthplace   222 non-null    object
 7   artist_nationality  1069 non-null   object
 8   artist_sex          265 non-null    object
 9   keywords            255 non-null    object
 10  type                2501 non-null   object
 11  technique           2201 non-null   object
 12  support             1867 non-null   object
 13  theme               393 non-null    object
 14  country             524 non-null    object
 15  year_start          2431 non-null   float64
 16  year_end            2431 non-null   float64
 17  estimated           2918 non-null   bool
 18  width_cm            2209 non-null   float64
 19  height_cm           2193 non-null   float64
 20  depth_cm            279 non-null    float64
 21  museum              2918 non-null   object
dtypes: bool(1), float64(5), object(16)
memory usage: 504.4+ KB

In [ ]:
df1.to_csv("data/obras_draft.csv", index=False)

In [ ]:
df_final.to_csv("data/artworks.csv", index=False)